### ISSUE TITLE
Reusing crate name `fs-tree` in crates.io

### ISSUE THREAD

**Issue by marcospb19** [rtgill82/fs-tree#1]
Hey @rtgill82 would you be willing to give out the name fs-tree because it was deprecated so that I could use it to publish a crate in the same place?

I wanted to make it so that people are able to load a tree of files in-memory and also make tree diffs from it.

Tree diffs are specially useful for comparing changes in the filesystem, and it's a nice building block for dotfiles managers.

Thanks in advance :)

**Comment by rtgill82** [comment]
Sure. I can transfer ownership to you. It seems there may be some people using the old crate though, and I suspect it will always exist in the crate history. I would suggest starting with an initial version of `0.2.0` or greater.

**Comment by marcospb19** [comment]
Thanks for the trust! I can keep previous versions intact, my username in `crates.io` is `marcospb19`, if you desire I can also ping you in this issue when I upload the a newest version of the crate.

**Comment by rtgill82** [comment]
Your welcome! I'm not sure how else I might be able to help, but go ahead and ping me when it's updated. I'll make sure everything seems to be working ok before I remove myself as maintainer.

**Comment by marcospb19** [comment]
Made the first release!

https://crates.io/crates/fs-tree

**Comment by rtgill82** [comment]
Looks good! I'll leave it all to you now.
